parserOptions:
  sourceType: 'module'

env:
  es6: true
  browser: true

extends: 'htmlacademy/es6'

rules:
  "semi": "off"
  "arrow-parens": "off"
  "comma-dangle": "off"
  "require-jsdoc": "off"
  "no-trailing-spaces": "off"
  "operator-linebreak": "off"

